// <auto-generated />
namespace StockDataBL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class primarykeychangeanddatetimefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primarykeychangeanddatetimefix));
        
        string IMigrationMetadata.Id
        {
            get { return "201907281126393_primary key change and datetime fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
